### ISSUE TITLE
Rework the UI

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#74]
...no mockups yet as I'm not a UI/UX designer.

But:
* there are a lot of input fields
* some of them could be hidden behind buttons, eg. server/pass, how often do you change that?
* some are hidden but once revealed (e2e stuff) you can't actually hide them back
* the whole input part could be hidden once sharing has started (eg. and make the countdown clock bigger), also those fields are already disabled anyway, right? Eg. make them enabled/pop-up if I hit Share again.
* the logo on top occupies too much space, yes you have the icon in the titlebar, move the github link there, make it clickable, use the view space for something useful.
* dark theme (yes my Android actually forces a dark theme, but not all users run Android 10)
* ...

**Comment by bilde2910** [comment]
I agree on these points. I'm no UI/UX designer either, but I think it's time for me to move some stuff to a separate "settings" screen that can be accessed from a menu in the top-right corner. That will allow me to fit a lot of different settings in there as well in addition to those I already have.

Plus it will make for a much cleaner interface. I'll look at it and see what I can do, but it'll be a big undertaking, so I'll hope to have some progress on this in v1.6 rather than the upcoming v1.5.2. (Or I could skip right to v1.6.)

**Comment by licaon-kter** [comment]
Move the STOP button on top, having gestures enabled I find myself touching the lower part of the screen rather often.

**Comment by bilde2910** [comment]
Here's current progress on moving settings to a separate menu, opened from the cog icon on the toolbar.

![hauk-settings-menu](https://user-images.githubusercontent.com/6617815/70668833-f9be3e00-1c74-11ea-9085-9917a3cd6610.png)

**Comment by licaon-kter** [comment]
Open Settings on first start, don't allow dismissing the Settings if Server is empty and there is no Password (at least)

Default Update interval, make it longer eg. 3-5 seconds, users might not bother setting it up and 1 sec is rather aggressive, battery wise.

If Group share, don't start if there's no Nickname setup.

**Comment by bilde2910** [comment]
I can set it up so that if the user presses "Start" when there is no server URL set, instead of starting the share, the Settings menu shows up and a [toast notification](https://developer.android.com/guide/topics/ui/notifiers/toasts) informs them that they have to set a server URL before they can start sharing.

**Comment by licaon-kter** [comment]
Touching the logo/github link should open that link.

Add in Settings a last section with app version (and server version if such thing is possible)

**Comment by licaon-kter** [comment]
The button layout is rather picky, I had **Stop** translated as **Oprire**, so the button had **OPRI** and **RE** on the second row, so I changed it to **Stop** (same meaning in many languages) only to find it rendered like this now:

![buttonlayout](https://user-images.githubusercontent.com/2282799/70813124-e02a0d00-1dc0-11ea-8b36-50238bb26ba6.jpg)

The strange part is that after some time (open, minimize the app), the button stretches to have the full word.

Can this layout be more flexible, to encompass the words fully if enough space is available?

**Comment by bilde2910** [comment]
I'm honestly not sure why that happens. It started after the first rework commit. I'm hoping that as I move the list of active shares away from the UI in #72, this will resolve itself. Otherwise I'll have to dig a bit more to see what's causing this to happen.

**Comment by bilde2910** [comment]
Current status:

>:heavy_check_mark: there are a lot of input fields
>:heavy_check_mark: some of them could be hidden behind buttons, eg. server/pass, how often do you change that?
>:heavy_check_mark: some are hidden but once revealed (e2e stuff) you can't actually hide them back

Resolved by moving these to the new settings menu

>:x: the whole input part could be hidden once sharing has started (eg. and make the countdown clock bigger), also those fields are already disabled anyway, right? Eg. make them enabled/pop-up if I hit Share again.
>:x: the logo on top occupies too much space, yes you have the icon in the titlebar, move the github link there, make it clickable, use the view space for something useful.

Now that the other input fields are gone, do you think these are still necessary? There's no longer any need to scroll down to see all the UI elements on the main page

>:heavy_check_mark: dark theme (yes my Android actually forces a dark theme, but not all users run Android 10)

Resolved by the past few commits

>:x: Move the STOP button on top, having gestures enabled I find myself touching the lower part of the screen rather often.

Connection settings have all been moved to the settings page, so the stop button is higher up now. Also wondering if maybe #78 could be a better solution here. However, I don't use gestures myself. What are your thoughts about this in light of the recent changes? I can't really comment much since I don't use gestures

>:heavy_check_mark: Open Settings on first start, don't allow dismissing the Settings if Server is empty and there is no Password (at least)

Resolved via toast notification

>:x: Default Update interval, make it longer eg. 3-5 seconds, users might not bother setting it up and 1 sec is rather aggressive, battery wise.

I realized I never actually commented on this. The device will use a lot of battery power for location services if the interval is set to 3 seconds too (maintaining a fix). 1 second was chosen because it provides the smoothest real-time view on the map given that there is currently no movement prediction on the frontend. I'm not really inclined to change this default right now

>:x: If Group share, don't start if there's no Nickname setup.
>:x: Touching the logo/github link should open that link.

To be implemented

>:x: Add in Settings a last section with app version (and server version if such thing is possible)

Good idea. Server version is returned by the server while a share is active, but actually accessing it in the settings menu will be difficult. I can certainly show the app version, though. To be implemented

>:x: Can this layout be more flexible, to encompass the words fully if enough space is available?

To be analyzed and fixed

**Comment by licaon-kter** [comment]
> Now that the other input fields are gone, do you think these are still necessary? There's no longer any need to scroll down to see all the UI elements on the main page

I guess not

> Connection settings have all been moved to the settings page, so the stop button is higher up now.

#78 is the fix yes.

> I can't really comment much since I don't use gestures

Gestures are a mainstay since Android 9, but I never managed to touch the button anyway, just that it "looks dangerous", again #78 will make this a moot point.

**Comment by licaon-kter** [comment]
Notification - show current/real status: "Location active" or "Searching location/GNSS", now it's always "active"

**Comment by bilde2910** [comment]
Current status:

>:heavy_check_mark: If Group share, don't start if there's no Nickname setup.
>:heavy_check_mark: Touching the logo/github link should open that link.

Done.

>:heavy_check_mark: Add in Settings a last section with app version (and server version if such thing is possible)

App version shown, along with link to source code and issue tracker.

>:heavy_check_mark: Can this layout be more flexible, to encompass the words fully if enough space is available?

Seems to be an Android bug causing this issue. Workaround live in latest commit; resolved, for all intents and purposes.

> :x: Notification - show current/real status: "Location active" or "Searching location/GNSS", now it's always "active"

To be implemented. I'm thinking some kind of configurable "time since last update" setting, i.e. fall back to coarse location again ("waiting for high-accuracy fix") if no accurate location has been received for e.g. 45 seconds since the last time it *should have* been received. What are your thoughts about this, and what do you think a sane default would be here?

**Comment by licaon-kter** [comment]
> I'm thinking some kind of configurable "time since last update" setting,

I have no thoughts here, 45 secs sounds ok

> Would it also be a good idea to show inaccurate, non-GNSS locations on the map in yellow or some other coloring instead of red?

Yes, please, I've seen some large (half the city) jumps in some cases so making these stand out helps.

**Comment by bilde2910** [comment]
> :heavy_check_mark: Notification - show current/real status: "Location active" or "Searching location/GNSS", now it's always "active"
> :heavy_check_mark: Would it also be a good idea to show inaccurate, non-GNSS locations on the map in yellow or some other coloring instead of red?

Implemented in latest commit. The status switches over automatically after (interval + timeout) time, where interval is your session's interval, and timeout defaults to 45 seconds but is configurable in settings.

All items in this issue are now resolved; closing. Thanks a lot for your suggestions! If there's anything else, feel free to create new issues :+1:

**Comment by licaon-kter** [comment]
Umm 
> Notification - show current/real status: "Location active" or "Searching location/GNSS", now it's always "active"

This is not fixed, the actual notification text is not in sync with in app location status. If app is "Searching for location..." the notification should mirror that state.

**Comment by bilde2910** [comment]
Oh, I fixed the wrong thing apparently. I'll try to fix the notification as well.

**Comment by bilde2910** [comment]
There, that should fix it :-)
